### ISSUE TITLE
Bug: improper checking for index and size for arrays

### ISSUE THREAD

**Issue by lgorbski** [wavesoftware/java-eid-exceptions#15]
https://github.com/wavesoftware/java-eid-exceptions/blob/e4015c4092efaf7701dee50f1edd33c211e64aff/src/main/java/pl/wavesoftware/eid/utils/EidPreconditions.java#L400

I think, it should be _return index < 0 || index >= size_;

**Comment by cardil** [comment]
Thanks for bug report. I will investigate that.

**Comment by cardil** [comment]
Fixed on PR #6 

Will be released as v2.0.0
